# Generated by Django 5.1.4 on 2025-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('prompt_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
